export const TOGGLE_SWITCH = "TOGGLE_SWITCH";
export const ASSIGN_WINNER = "ASSIGN_WINNER";
export const ASSIGN_WINNER_SQUARES = "ASSIGN_WINNER_SQUARES";
export const CHANGE_GAME_STATE = "CHANGE_GAME_STATE";